# Generated by Django 3.2.16 on 2023-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../IMG_0038_lm65ne', upload_to='images/'),
        ),
    ]
